version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "alexasolutions"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fhffnnsekhs6"
s3_prefix = "alexasolutions"
region = "us-east-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
